openapi: 3.0.0
info:
  description: This is a sample server Recordstore server. For this sample, you can use
    the api key `special-key` to test the authorization filters.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: OpenAPI Recordstore
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080
tags:
- description: Everything about your Records
  name: record
paths:
  /record/search:
    post:
      description: Search records.
      operationId: search
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:          # <!--- form field name
                  type: string
                endDate:            # <!--- form field name
                  type: string
                minCount:           # <!--- form field name
                  type: integer
                maxCount:           # <!--- form field name
                  type: integer
              required:
                - startDate
                - endDate
                - minCount
                - maxCount
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Record'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Record'
                type: array
          description: successful operation
        "400":
          description: Invalid tag value
      summary: Finds Records by tags
      x-eov-operation-handler: controllers/RecordController
components:
  requestBodies:
    Record:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Record'
        application/xml:
          schema:
            $ref: '#/components/schemas/Record'
      description: Record object that needs to be added to the store
      required: true
  schemas:
    Record:
      description: A record for sale in the record store
      example:
        key: TAKwGc6Jr4i8Z487
        createdAt: "2017-01-28T01:22:14.398Z"
        totalCount: 2800
      properties:
        key:
          example: TAKwGc6Jr4i8Z487
          type: string
        createdAt:
          example: "2017-01-28T01:22:14.398Z"
          type: string
        totalCount:
          example: 2800
          type: integer
      required:
      - totalCount
      title: a Record
      type: object
      xml:
        name: Record
    ApiResponse:
      description: Describes the result of uploading an image resource
      example:
        code: 0
        type: type
        message: message
      properties:
        code:
          format: int32
          type: integer
        type:
          type: string
        message:
          type: string
      title: An uploaded response
      type: object
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey
